"""ETH v4 - FRACTIONAL-EXPOSURE low-MDD portfolio (13 legs).

WHY A SEPARATE FILE (v4)
------------------------
* BTC parent, ETH v1, v2 and v3 are all frozen. We add a new file.
* v1/v2/v3 use the parent's execution model: collapse all legs into ONE net
  direction by majority vote and hold a SINGLE +/-100%% position. That binary
  sizing is the main reason their MDD could not go below ~16%%.

EXECUTION MODEL - FRACTIONAL EXPOSURE (the key difference)
---------------------------------------------------------
v4 keeps the parent's leg state machine but OVERRIDES ``_reconcile`` to size the
single position in proportion to vote CONVICTION rather than betting 100%% on
the majority:

    raw      = (long_legs - short_legs) / n_legs * SCALE
    target   = quantize(clip(raw, -MAX_EXP, +MAX_EXP), STEP)   # signed weight
    position = target  (via ctx.enter_long/short(entry_pct=|target|))

When the target exposure bucket changes the strategy closes and re-enters at the
new size (the backtest engine has no partial resize), so every resize / flip /
flatten is a trade. Average gross exposure is small (~0.14), which is
exactly why drawdowns are much smaller than the +/-100%% models.

SELECTION (scripts/_alpha_lab/_eth_v4_optimize.py)
--------------------------------------------------
Random-restart greedy over the candidate leg pool, evaluated under the REAL
fractional-exposure single-account model (commission charged as close+re-enter
on every bucket change). Objective: minimise MDD subject to >=1 trade/day and
every calendar year positive.

PERFORMANCE - fractional-exposure model, commission 0.0004 both sides
---------------------------------------------------------------------
# FULL 2022-01..2026-06 : ret +48.4%  MDD 14.5%  +months 57.4%  worst -7.1%  ~1.58 trades/day
# HOLDOUT 2025-01..2026-05: ret +5.7%  MDD 14.5%  +months 47.1%  worst -5.2%
# Per-calendar-year (every year positive, incl. the 2022 and 2025 bears):
#   2022: ret +13.9%  MDD 13.6%  +months 67%  worst -7.1%
#   2023: ret +3.2%  MDD 10.8%  +months 67%  worst -3.8%
#   2024: ret +18.7%  MDD 14.1%  +months 50%  worst -3.9%
#   2025: ret +2.8%  MDD 14.4%  +months 50%  worst -5.2%
#   2026: ret +3.4%  MDD 14.3%  +months 50%  worst -3.7%
#
# vs v3 (~16%% MDD, ~0.4 trades/day): v4 has a LOWER MDD AND >=1 trade/day,
# thanks to conviction-proportional sizing. This is the smoother, lower-drawdown
# curve that the binary majority-vote models structurally could not produce.

RUNTIME CONTRACT
----------------
Reuses the parent lifecycle, data loaders, REST providers, signal funcs and
per-leg state machine. ``resolve_legs`` / ``_symbol_supported`` are scope-patched
during ``initialize`` (like v1/v2/v3); ``_reconcile`` is overridden on the
subclass so the parent and v1/v2/v3 are unaffected.
"""
from __future__ import annotations

import logging
from typing import Any

from scripts.strategies import multi_factor_portfolio_strategy as _mfp
from scripts.strategies.multi_factor_portfolio_strategy import (
    MultiFactorPortfolioStrategy,
)

from strategy.context import StrategyContext

logger = logging.getLogger(__name__)

BASELINE_SYMBOL = "ETHUSDT"
STRATEGY_ID = "multi_factor_portfolio_eth_v4"

# Fractional-exposure mapping (discovered).
EXPOSURE_SCALE = 2.5
EXPOSURE_MAX = 0.5
EXPOSURE_STEP = 0.15


# ---------------------------------------------------------------------------
# v4 legs - 13 fully-specified legs (real fractional-model validated).
# Generated by scripts/_alpha_lab/_gen_eth_v4_from_realmodel.py - do not edit.
# ---------------------------------------------------------------------------
ETH_V4_LEGS: list[dict[str, Any]] = [
    {"family": "donchian_breakout", "config": {"interval_min": 240, "dc_period": 20, "atr_min_mult": 0.0, "use_oi": False, "oi_lb": 96, "oi_min_for_long": 0.0, "oi_max_for_short": -0.01, "tp_pct": 0.04, "sl_pct": 0.015, "max_hold_h": 48, "side": "both"}},  # noqa: E501
    {"family": "donchian_breakout", "config": {"interval_min": 120, "dc_period": 48, "atr_min_mult": 0.0, "use_oi": False, "oi_lb": 96, "oi_min_for_long": 0.0, "oi_max_for_short": -0.01, "tp_pct": 0.08, "sl_pct": 0.025, "max_hold_h": 72, "side": "short_only"}},  # noqa: E501
    {"family": "ensemble_meanrev", "config": {"interval_min": 60, "bb_period": 20, "bb_std": 2.0, "rsi_period": 14, "rsi_long": 40.0, "rsi_short": 60.0, "oi_lb": 96, "oi_drop": -0.015, "oi_pop": 0.02, "taker_lb": 96, "taker_long_max": 0.93, "taker_short_min": 1.07, "lsr_z_lookback": 480, "lsr_z_long": -1.0, "lsr_z_short": 1.5, "min_votes": 3, "use_trend_filter": True, "trend_ema": 200, "use_atr_filter": True, "atr_min_pct": 0.0025, "atr_max_pct": 0.025, "tp_pct": 0.012, "sl_pct": 0.012, "max_hold_h": 16, "side": "both"}},  # noqa: E501
    {"family": "donchian_breakout", "config": {"interval_min": 120, "dc_period": 96, "atr_min_mult": 0.0, "use_oi": False, "oi_lb": 96, "oi_min_for_long": 0.0, "oi_max_for_short": -0.01, "tp_pct": 0.15, "sl_pct": 0.04, "max_hold_h": 36, "side": "short_only"}},  # noqa: E501
    {"family": "donchian_breakout", "config": {"interval_min": 30, "dc_period": 96, "atr_min_mult": 0.0, "use_oi": False, "oi_lb": 96, "oi_min_for_long": 0.0, "oi_max_for_short": -0.01, "tp_pct": 0.15, "sl_pct": 0.04, "max_hold_h": 12, "side": "long_only"}},  # noqa: E501
    {"family": "lsr_taker_confluence", "config": {"interval_min": 15, "lsr_lb": 240, "z_lsr_long": -1.0, "z_lsr_short": 1.5, "use_taker": True, "taker_lb": 240, "z_taker_long": -1.0, "z_taker_short": 1.0, "lsr_col": "lsr_count", "use_rsi": True, "rsi_long": 35.0, "rsi_short": 60.0, "tp_pct": 0.018, "sl_pct": 0.008, "max_hold_h": 16, "side": "short_only"}},  # noqa: E501
    {"family": "donchian_breakout", "config": {"interval_min": 120, "dc_period": 192, "atr_min_mult": 0.0, "use_oi": False, "oi_lb": 96, "oi_min_for_long": 0.0, "oi_max_for_short": -0.01, "tp_pct": 0.04, "sl_pct": 0.015, "max_hold_h": 72, "side": "both"}},  # noqa: E501
    {"family": "donchian_breakout", "config": {"interval_min": 240, "dc_period": 48, "atr_min_mult": 0.0, "use_oi": False, "oi_lb": 96, "oi_min_for_long": 0.0, "oi_max_for_short": -0.01, "tp_pct": 0.04, "sl_pct": 0.015, "max_hold_h": 48, "side": "both"}},  # noqa: E501
    {"family": "donchian_breakout", "config": {"interval_min": 120, "dc_period": 96, "atr_min_mult": 0.0, "use_oi": False, "oi_lb": 96, "oi_min_for_long": 0.0, "oi_max_for_short": -0.01, "tp_pct": 0.04, "sl_pct": 0.015, "max_hold_h": 72, "side": "short_only"}},  # noqa: E501
    {"family": "donchian_breakout", "config": {"interval_min": 240, "dc_period": 192, "atr_min_mult": 0.0, "use_oi": False, "oi_lb": 96, "oi_min_for_long": 0.0, "oi_max_for_short": -0.01, "tp_pct": 0.15, "sl_pct": 0.04, "max_hold_h": 48, "side": "long_only"}},  # noqa: E501
    {"family": "lsr_taker_confluence", "config": {"interval_min": 15, "lsr_lb": 240, "z_lsr_long": -1.0, "z_lsr_short": 1.5, "use_taker": True, "taker_lb": 240, "z_taker_long": -1.0, "z_taker_short": 1.0, "lsr_col": "lsr_count", "use_rsi": True, "rsi_long": 35.0, "rsi_short": 60.0, "tp_pct": 0.012, "sl_pct": 0.012, "max_hold_h": 8, "side": "both"}},  # noqa: E501
    {"family": "ensemble_meanrev", "config": {"interval_min": 60, "bb_period": 20, "bb_std": 2.0, "rsi_period": 14, "rsi_long": 40.0, "rsi_short": 60.0, "oi_lb": 96, "oi_drop": -0.015, "oi_pop": 0.02, "taker_lb": 96, "taker_long_max": 0.93, "taker_short_min": 1.07, "lsr_z_lookback": 480, "lsr_z_long": -1.0, "lsr_z_short": 1.5, "min_votes": 3, "use_trend_filter": True, "trend_ema": 200, "use_atr_filter": True, "atr_min_pct": 0.0025, "atr_max_pct": 0.025, "tp_pct": 0.012, "sl_pct": 0.012, "max_hold_h": 8, "side": "short_only"}},  # noqa: E501
    {"family": "donchian_breakout", "config": {"interval_min": 240, "dc_period": 192, "atr_min_mult": 0.0, "use_oi": False, "oi_lb": 96, "oi_min_for_long": 0.0, "oi_max_for_short": -0.01, "tp_pct": 0.08, "sl_pct": 0.025, "max_hold_h": 48, "side": "long_only"}},  # noqa: E501
]


def resolve_legs(symbol: str) -> list[dict[str, Any]]:
    sym = symbol.upper()
    if sym != BASELINE_SYMBOL:
        raise ValueError(
            f"MultiFactorPortfolioEthV4Strategy: symbol {sym} is not "
            f"supported; this strategy is tuned exclusively for "
            f"{BASELINE_SYMBOL}."
        )
    return ETH_V4_LEGS


def _symbol_supported(symbol: str) -> bool:
    return symbol.upper() == BASELINE_SYMBOL


def _target_exposure(long_count: int, short_count: int, n_legs: int) -> float:
    """Conviction-proportional signed exposure, quantized to STEP buckets."""
    if n_legs <= 0:
        return 0.0
    raw = (long_count - short_count) / n_legs * EXPOSURE_SCALE
    raw = max(-EXPOSURE_MAX, min(EXPOSURE_MAX, raw))
    if EXPOSURE_STEP > 0:
        raw = round(raw / EXPOSURE_STEP) * EXPOSURE_STEP
    return float(raw)


STRATEGY_PARAMS: dict[str, Any] = dict(_mfp.STRATEGY_PARAMS)
STRATEGY_PARAM_SCHEMA: list[dict[str, Any]] = list(_mfp.STRATEGY_PARAM_SCHEMA)


class MultiFactorPortfolioEthV4Strategy(MultiFactorPortfolioStrategy):
    """ETH v4 - 13-leg fractional-exposure low-MDD multi-factor portfolio.

    Identical lifecycle to the parent, but ``_reconcile`` sizes the single
    position in proportion to vote conviction (fractional exposure) instead of
    the parent's +/-100%% majority vote, which lowers drawdown while keeping
    >=1 trade/day.
    """

    def initialize(self, ctx: StrategyContext) -> None:
        ctx_symbol = getattr(ctx, "symbol", None)
        if ctx_symbol and str(ctx_symbol).upper() != BASELINE_SYMBOL:
            raise ValueError(
                f"MultiFactorPortfolioEthV4Strategy: ctx.symbol={ctx_symbol} "
                f"is not supported; tuned exclusively for {BASELINE_SYMBOL}."
            )
        self._committed_exposure: float = 0.0
        orig_resolve = _mfp.resolve_legs
        orig_supported = _mfp._symbol_supported
        _mfp.resolve_legs = resolve_legs
        _mfp._symbol_supported = _symbol_supported
        try:
            super().initialize(ctx)
        finally:
            _mfp.resolve_legs = orig_resolve
            _mfp._symbol_supported = orig_supported

    def _reconcile(self, ctx: StrategyContext, target: int, long_count: int,
                   short_count: int, ts: int) -> None:
        """Override: size the single position by fractional exposure.

        Closes and re-enters whenever the quantized target exposure bucket
        changes (the backtest engine cannot partially resize). ``target`` (the
        parent's net sign) is ignored in favour of the conviction-weighted
        exposure.
        """
        n_legs = len(self._legs)
        target_exp = _target_exposure(long_count, short_count, n_legs)

        # Sync committed exposure with reality (external close, SL, etc.).
        pos = getattr(ctx, "position", None)
        cur_size = 0.0
        if pos is not None:
            try:
                cur_size = float(getattr(pos, "size", 0.0) or 0.0)
            except (TypeError, ValueError):
                cur_size = 0.0
        if abs(cur_size) < 1e-12:
            self._committed_exposure = 0.0

        if abs(target_exp - self._committed_exposure) < 1e-9:
            return  # same bucket - hold

        # Close any existing position, then re-enter at the new exposure.
        if abs(cur_size) > 1e-12:
            try:  # noqa: SIM105
                ctx.close_position(
                    reason=f"MFP-v4 resize {self._committed_exposure:+.2f}"
                           f"->{target_exp:+.2f}")
            except Exception:  # noqa: BLE001, S110
                pass
        mag = abs(target_exp)
        if target_exp > 1e-9:
            ctx.enter_long(
                reason=f"MFP-v4 long exp={mag:.2f} "
                       f"({long_count}L/{short_count}S)", entry_pct=mag)
            self._committed_side = 1
        elif target_exp < -1e-9:
            ctx.enter_short(
                reason=f"MFP-v4 short exp={mag:.2f} "
                       f"({long_count}L/{short_count}S)", entry_pct=mag)
            self._committed_side = -1
        else:
            self._committed_side = 0
        self._committed_exposure = target_exp
