FROM python:3.12-slim

ENV TZ=UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /app
COPY . /app

ENV PYTHONPATH=/app/src

RUN pip install --no-cache-dir uv
RUN uv sync

CMD ["uv", "run", "python", "-m", "runner.main"]

